/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimulateRouteImport } from './routes/simulate'
import { Route as VisualizeRouteImport } from './routes/visualize'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateRoute = SimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizeRoute = VisualizeRouteImport.update({
  id: '/visualize',
  path: '/visualize',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/simulate': typeof SimulateRoute
  '/visualize': typeof VisualizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/simulate': typeof SimulateRoute
  '/visualize': typeof VisualizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/simulate': typeof SimulateRoute
  '/visualize': typeof VisualizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/simulate' | '/visualize'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/simulate' | '/visualize'
  id: '__root__' | '/' | '/simulate' | '/visualize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SimulateRoute: typeof SimulateRoute
  VisualizeRoute: typeof VisualizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulate': {
      id: '/simulate'
      path: '/simulate'
      fullPath: '/simulate'
      preLoaderRoute: typeof SimulateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualize': {
      id: '/visualize'
      path: '/visualize'
      fullPath: '/visualize'
      preLoaderRoute: typeof VisualizeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SimulateRoute: SimulateRoute,
  VisualizeRoute: VisualizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
